annotations:
  application.giantswarm.io/team: "rocket"
  application.giantswarm.io/app-type: "bundle"
apiVersion: v2
description: A Helm chart which defines the pre-installed apps in all Giant Swarm vSphere clusters
home: https://github.com/giantswarm/default-apps-vsphere
name: default-apps-vsphere
restrictions:
  compatibleProviders:
    - vsphere
version: 0.8.0
